export interface TextTemplate {
  name: string;
  content: string;
  preview: string;
  category: "titles" | "body" | "stylized" | "lower-thirds" | "captions";
  styles: Record<string, any>;
}

export const textOverlayTemplates: Record<string, TextTemplate> = {
  // ── Titles ──
  modern: {
    name: "Modern Title",
    content: "Modern Title",
    preview: "Sleek & Minimalist",
    category: "titles",
    styles: {
      fontSize: "2.8rem",
      fontWeight: "700",
      color: "#FFFFFF",
      backgroundColor: "",
      fontFamily: "font-sans",
      fontStyle: "normal",
      textDecoration: "none",
      lineHeight: "1.1",
      textAlign: "center",
      letterSpacing: "-0.03em",
    },
  },
  impact: {
    name: "Impact Statement",
    content: "MAKE AN IMPACT",
    preview: "Bold & Commanding",
    category: "titles",
    styles: {
      fontSize: "3.5rem",
      fontWeight: "900",
      color: "#FFFFFF",
      backgroundColor: "",
      fontFamily: "font-sans",
      fontStyle: "normal",
      textDecoration: "none",
      lineHeight: "1",
      textAlign: "center",
      letterSpacing: "0.02em",
      textTransform: "uppercase",
      textShadow: "2px 2px 0px rgba(0, 0, 0, 0.2)",
    },
  },
  cinematic: {
    name: "Cinematic",
    content: "CINEMATIC",
    preview: "Wide Spaced & Elegant",
    category: "titles",
    styles: {
      fontSize: "3rem",
      fontWeight: "300",
      color: "#FFFFFF",
      backgroundColor: "",
      fontFamily: "font-sans",
      fontStyle: "normal",
      textDecoration: "none",
      lineHeight: "1.2",
      textAlign: "center",
      letterSpacing: "0.5em",
      textTransform: "uppercase",
    },
  },
  serif: {
    name: "Serif Title",
    content: "Elegant Title",
    preview: "Classic & Refined",
    category: "titles",
    styles: {
      fontSize: "3rem",
      fontWeight: "700",
      color: "#FFFFFF",
      backgroundColor: "",
      fontFamily: "Georgia, serif",
      fontStyle: "normal",
      textDecoration: "none",
      lineHeight: "1.2",
      textAlign: "center",
      letterSpacing: "-0.01em",
    },
  },

  // ── Body ──
  subtitle: {
    name: "Subtitle",
    content: "Your subtitle goes here",
    preview: "Clean & Readable",
    category: "body",
    styles: {
      fontSize: "1.6rem",
      fontWeight: "400",
      color: "#E0E0E0",
      backgroundColor: "",
      fontFamily: "font-sans",
      fontStyle: "normal",
      textDecoration: "none",
      lineHeight: "1.5",
      textAlign: "center",
      letterSpacing: "0.01em",
    },
  },
  bodyText: {
    name: "Body Text",
    content: "Add your paragraph text here for longer descriptions.",
    preview: "Paragraph Style",
    category: "body",
    styles: {
      fontSize: "1.4rem",
      fontWeight: "400",
      color: "#D4D4D4",
      backgroundColor: "",
      fontFamily: "font-sans",
      fontStyle: "normal",
      textDecoration: "none",
      lineHeight: "1.6",
      textAlign: "left",
      letterSpacing: "0",
    },
  },
  quote: {
    name: "Quote",
    content: "\u201CWords can inspire.\u201D",
    preview: "Italic & Inspirational",
    category: "body",
    styles: {
      fontSize: "2rem",
      fontWeight: "400",
      color: "#E0E0E0",
      backgroundColor: "",
      fontFamily: "Georgia, serif",
      fontStyle: "italic",
      textDecoration: "none",
      lineHeight: "1.5",
      textAlign: "center",
      letterSpacing: "0",
    },
  },
  callout: {
    name: "Callout",
    content: "Important note here",
    preview: "Left Border Accent",
    category: "body",
    styles: {
      fontSize: "1.5rem",
      fontWeight: "500",
      color: "#FFFFFF",
      backgroundColor: "rgba(255,255,255,0.05)",
      fontFamily: "font-sans",
      fontStyle: "normal",
      textDecoration: "none",
      lineHeight: "1.5",
      textAlign: "left",
      padding: "12px 16px 12px 20px",
      borderRadius: "4px",
      border: "none",
      borderLeft: "3px solid #6366F1",
    },
  },

  // ── Stylized ──
  gradient: {
    name: "Gradient Pop",
    content: "Gradient Style",
    preview: "Dynamic & Modern",
    category: "stylized",
    styles: {
      fontSize: "3.2rem",
      fontWeight: "800",
      background:
        "linear-gradient(135deg, #6366F1 0%, #EC4899 50%, #F59E0B 100%)",
      WebkitBackgroundClip: "text",
      WebkitTextFillColor: "transparent",
      fontFamily: "font-sans",
      fontStyle: "normal",
      textDecoration: "none",
      lineHeight: "1.1",
      textAlign: "center",
      textShadow: "0px 0px 20px rgba(236, 72, 153, 0.3)",
    },
  },
  highlight: {
    name: "Highlight Box",
    content: "Highlighted Text",
    preview: "Modern & Distinctive",
    category: "stylized",
    styles: {
      fontSize: "2.4rem",
      fontWeight: "700",
      color: "#FFFFFF",
      backgroundColor: "rgba(79, 70, 229, 0.85)",
      fontFamily: "font-sans",
      fontStyle: "normal",
      textDecoration: "none",
      lineHeight: "1.2",
      padding: "16px 32px",
      borderRadius: "12px",
      textAlign: "center",
      boxShadow:
        "0 8px 16px -4px rgba(79, 70, 229, 0.25), 0 4px 6px -2px rgba(0, 0, 0, 0.1)",
      backdropFilter: "blur(8px)",
      border: "1px solid rgba(255, 255, 255, 0.1)",
    },
  },
  neon: {
    name: "Neon Glow",
    content: "NEON",
    preview: "Glowing & Vibrant",
    category: "stylized",
    styles: {
      fontSize: "3.5rem",
      fontWeight: "700",
      color: "#00FF88",
      backgroundColor: "",
      fontFamily: "font-sans",
      fontStyle: "normal",
      textDecoration: "none",
      lineHeight: "1.1",
      textAlign: "center",
      textShadow:
        "0 0 10px #00FF88, 0 0 20px #00FF88, 0 0 40px #00FF88, 0 0 80px #00AA55",
    },
  },
  outline: {
    name: "Outline Text",
    content: "OUTLINE",
    preview: "Stroke Only",
    category: "stylized",
    styles: {
      fontSize: "3.5rem",
      fontWeight: "900",
      color: "transparent",
      backgroundColor: "",
      fontFamily: "font-sans",
      fontStyle: "normal",
      textDecoration: "none",
      lineHeight: "1.1",
      textAlign: "center",
      WebkitTextStroke: "2px #FFFFFF",
      letterSpacing: "0.05em",
      textTransform: "uppercase",
    },
  },
  glitch: {
    name: "Glitch",
    content: "GLITCH",
    preview: "Distorted & Edgy",
    category: "stylized",
    styles: {
      fontSize: "3.2rem",
      fontWeight: "900",
      color: "#FFFFFF",
      backgroundColor: "",
      fontFamily: "font-mono, monospace",
      fontStyle: "normal",
      textDecoration: "none",
      lineHeight: "1.1",
      textAlign: "center",
      textTransform: "uppercase",
      textShadow: "3px 0 #FF0000, -3px 0 #00FFFF",
      letterSpacing: "0.05em",
    },
  },
  retro: {
    name: "Retro",
    content: "RETRO",
    preview: "Vintage Vibes",
    category: "stylized",
    styles: {
      fontSize: "3rem",
      fontWeight: "800",
      color: "#FFD700",
      backgroundColor: "",
      fontFamily: "font-sans",
      fontStyle: "italic",
      textDecoration: "none",
      lineHeight: "1.1",
      textAlign: "center",
      textShadow:
        "3px 3px 0 #FF6B35, 6px 6px 0 rgba(0,0,0,0.2)",
      letterSpacing: "0.03em",
      textTransform: "uppercase",
    },
  },

  // ── Lower Thirds ──
  lowerThird: {
    name: "Lower Third",
    content: "John Doe",
    preview: "Name Tag Style",
    category: "lower-thirds",
    styles: {
      fontSize: "1.8rem",
      fontWeight: "600",
      color: "#FFFFFF",
      backgroundColor: "rgba(0, 0, 0, 0.7)",
      fontFamily: "font-sans",
      fontStyle: "normal",
      textDecoration: "none",
      lineHeight: "1.3",
      textAlign: "left",
      padding: "10px 20px",
      borderRadius: "4px",
      borderLeft: "3px solid #3B82F6",
      backdropFilter: "blur(8px)",
    },
  },
  tag: {
    name: "Tag",
    content: "#trending",
    preview: "Pill Badge",
    category: "lower-thirds",
    styles: {
      fontSize: "1.2rem",
      fontWeight: "600",
      color: "#FFFFFF",
      backgroundColor: "rgba(99, 102, 241, 0.9)",
      fontFamily: "font-sans",
      fontStyle: "normal",
      textDecoration: "none",
      lineHeight: "1",
      textAlign: "center",
      padding: "8px 20px",
      borderRadius: "999px",
    },
  },

  // ── Captions ──
  captionClassic: {
    name: "Classic Caption",
    content: "Classic caption style",
    preview: "White on dark bg",
    category: "captions",
    styles: {
      fontSize: "2.2rem",
      fontWeight: "600",
      color: "#FFFFFF",
      backgroundColor: "rgba(0, 0, 0, 0.7)",
      fontFamily: "font-sans",
      fontStyle: "normal",
      textDecoration: "none",
      lineHeight: "1.4",
      textAlign: "center",
      padding: "8px 16px",
      borderRadius: "4px",
    },
  },
  captionMinimal: {
    name: "Minimal Caption",
    content: "Minimal caption style",
    preview: "Clean & simple",
    category: "captions",
    styles: {
      fontSize: "2rem",
      fontWeight: "400",
      color: "#FFFFFF",
      backgroundColor: "",
      fontFamily: "font-sans",
      fontStyle: "normal",
      textDecoration: "none",
      lineHeight: "1.4",
      textAlign: "center",
      textShadow: "1px 1px 3px rgba(0,0,0,0.8)",
    },
  },
  captionNeon: {
    name: "Neon Caption",
    content: "Neon caption style",
    preview: "Glowing text",
    category: "captions",
    styles: {
      fontSize: "2.4rem",
      fontWeight: "700",
      color: "#00FF88",
      backgroundColor: "",
      fontFamily: "font-sans",
      fontStyle: "normal",
      textDecoration: "none",
      lineHeight: "1.4",
      textAlign: "center",
      textShadow: "0 0 10px #00FF88, 0 0 20px #00FF88, 0 0 40px #00AA55",
    },
  },
  captionBold: {
    name: "Bold Caption",
    content: "BOLD CAPTION STYLE",
    preview: "Impact & bold",
    category: "captions",
    styles: {
      fontSize: "2.8rem",
      fontWeight: "900",
      color: "#FFFFFF",
      backgroundColor: "",
      fontFamily: "font-sans",
      fontStyle: "normal",
      textDecoration: "none",
      lineHeight: "1.2",
      textAlign: "center",
      textTransform: "uppercase",
      textShadow: "2px 2px 0px rgba(0,0,0,0.5)",
      letterSpacing: "0.02em",
    },
  },
};

export const TEXT_CATEGORIES = [
  { id: "titles", label: "Titles" },
  { id: "body", label: "Body" },
  { id: "stylized", label: "Stylized" },
  { id: "lower-thirds", label: "Lower Thirds" },
  { id: "captions", label: "Captions" },
] as const;
